name: Publish NuGet Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.306"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build package
        run: dotnet build -c Release

      - name: Pack NuGet package
        run: dotnet pack

      - name: Push NuGet package
        run: dotnet nuget push ./src/Shared/bin/Debug/Fra.SharedLibrary.*.nupkg --source "nuget.org" --api-key ${{ secrets.NUGET_API_KEY }}
